name: ces
description: The most fast cryptocurrency exchange mobile app to buy, sell, trade, and earn cryptocurrencies
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
